name: QA Pipeline

on:
  push:
    branches:
      - qa
  pull_request:
    branches:
      - qa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK for QA
        uses: actions/upload-artifact@v3
        with:
          name: qa-apk
          path: build/app/outputs/flutter-apk/app-release.apk